export const countryData = [
  { country: "China", capital: "Beijing" },
  { country: "India", capital: "New Delhi" },
  { country: "United States", capital: "Washington, D.C." },
  { country: "Indonesia", capital: "Jakarta" },
  { country: "Pakistan", capital: "Islamabad" },
  { country: "Brazil", capital: "Brasília" },
  { country: "Nigeria", capital: "Abuja" },
  { country: "Bangladesh", capital: "Dhaka" },
  { country: "Russia", capital: "Moscow" },
  { country: "Mexico", capital: "Mexico City" },
  { country: "Japan", capital: "Tokyo" },
  { country: "Ethiopia", capital: "Addis Ababa" },
  { country: "Philippines", capital: "Manila" },
  { country: "Egypt", capital: "Cairo" },
  { country: "Vietnam", capital: "Hanoi" },
  { country: "DR Congo", capital: "Kinshasa" },
  { country: "Turkey", capital: "Ankara" },
  { country: "Iran", capital: "Tehran" },
  { country: "Germany", capital: "Berlin" },
  { country: "Thailand", capital: "Bangkok" },
  { country: "United Kingdom", capital: "London" },
  { country: "France", capital: "Paris" },
  { country: "Italy", capital: "Rome" },
  { country: "South Africa", capital: "Pretoria" },
  { country: "Myanmar", capital: "Naypyidaw" },
  { country: "Kenya", capital: "Nairobi" },
  { country: "South Korea", capital: "Seoul" },
  { country: "Colombia", capital: "Bogotá" },
  { country: "Spain", capital: "Madrid" },
  { country: "Uganda", capital: "Kampala" },
  { country: "Argentina", capital: "Buenos Aires" },
  { country: "Sudan", capital: "Khartoum" },
  { country: "Ukraine", capital: "Kyiv" },
  { country: "Iraq", capital: "Baghdad" },
  { country: "Afghanistan", capital: "Kabul" },
  { country: "Poland", capital: "Warsaw" },
  { country: "Canada", capital: "Ottawa" },
  { country: "Morocco", capital: "Rabat" },
  { country: "Saudi Arabia", capital: "Riyadh" },
  { country: "Uzbekistan", capital: "Tashkent" },
  { country: "Peru", capital: "Lima" },
  { country: "Malaysia", capital: "Kuala Lumpur" },
  { country: "Angola", capital: "Luanda" },
  { country: "Mozambique", capital: "Maputo" },
  { country: "Ghana", capital: "Accra" },
  { country: "Yemen", capital: "Sana'a" },
  { country: "Nepal", capital: "Kathmandu" },
  { country: "Venezuela", capital: "Caracas" },
  { country: "Madagascar", capital: "Antananarivo" },
  { country: "Cameroon", capital: "Yaoundé" },
  { country: "Côte d'Ivoire", capital: "Yamoussoukro" },
  { country: "North Korea", capital: "Pyongyang" },
  { country: "Australia", capital: "Canberra" },
  { country: "Niger", capital: "Niamey" },
  { country: "Taiwan", capital: "Taipei" },
  { country: "Sri Lanka", capital: "Colombo" },
  { country: "Burkina Faso", capital: "Ouagadougou" },
  { country: "Mali", capital: "Bamako" },
  { country: "Romania", capital: "Bucharest" },
  { country: "Malawi", capital: "Lilongwe" },
  { country: "Syria", capital: "Damascus" },
  { country: "Kazakhstan", capital: "Nur-Sultan" },
  { country: "Zambia", capital: "Lusaka" },
  { country: "Congo", capital: "Brazzaville" },
  { country: "Honduras", capital: "Tegucigalpa" },
  { country: "Nicaragua", capital: "Managua" },
  { country: "El Salvador", capital: "San Salvador" },
  { country: "Costa Rica", capital: "San José" },
  { country: "Uruguay", capital: "Montevideo" },
  { country: "Jamaica", capital: "Kingston" },
  { country: "Guyana", capital: "Georgetown" },
  { country: "Suriname", capital: "Paramaribo" },
  { country: "Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Chile", capital: "Santiago" },
  { country: "Ecuador", capital: "Quito" },
  { country: "Cuba", capital: "Havana" },
  { country: "Bolivia", capital: "La Paz" },
  { country: "Haiti", capital: "Port-au-Prince" },
  { country: "Paraguay", capital: "Asunción" },
  { country: "Honduras", capital: "Tegucigalpa" },
  { country: "Nicaragua", capital: "Managua" },
  { country: "Panama", capital: "Panama City" },
  { country: "Uruguay", capital: "Montevideo" },
  { country: "Jamaica", capital: "Kingston" },
  { country: "Guyana", capital: "Georgetown" },
  { country: "Suriname", capital: "Paramaribo" },
  { country: "Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "Trinidad and Tobago", capital: "Port of Spain" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "Trinidad and Tobago", capital: "Port of Spain" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "Trinidad and Tobago", capital: "Port of Spain" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "Trinidad and Tobago", capital: "Port of Spain" },
  { country: "Trinidad and Tobago", capital: "Port of Spain" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "The Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "The Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "The Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "The Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "The Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "The Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "The Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "The Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "The Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "The Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
  { country: "The Bahamas", capital: "Nassau" },
  { country: "Barbados", capital: "Bridgetown" },
  { country: "Saint Lucia", capital: "Castries" },
  { country: "Grenada", capital: "St. George's" },
  { country: "Dominica", capital: "Roseau" },
  { country: "Antigua and Barbuda", capital: "St. John's" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre" },
  { country: "Belize", capital: "Belmopan" },
];
