export const countryData = [
  { country: "China", city: "Beijing" },
  { country: "India", city: "New Delhi" },
  { country: "United States", city: "Washington, D.C." },
  { country: "Indonesia", city: "Jakarta" },
  { country: "Pakistan", city: "Islamabad" },
  { country: "Brazil", city: "Brasília" },
  { country: "Nigeria", city: "Abuja" },
  { country: "Bangladesh", city: "Dhaka" },
  { country: "Russia", city: "Moscow" },
  { country: "Mexico", city: "Mexico City" },
  { country: "Japan", city: "Tokyo" },
  { country: "Ethiopia", city: "Addis Ababa" },
  { country: "Philippines", city: "Manila" },
  { country: "Egypt", city: "Cairo" },
  { country: "Vietnam", city: "Hanoi" },
  { country: "DR Congo", city: "Kinshasa" },
  { country: "Turkey", city: "Ankara" },
  { country: "Iran", city: "Tehran" },
  { country: "Germany", city: "Berlin" },
  { country: "Thailand", city: "Bangkok" },
  { country: "United Kingdom", city: "London" },
  { country: "France", city: "Paris" },
  { country: "Italy", city: "Rome" },
  { country: "South Africa", city: "Pretoria" },
  { country: "Myanmar", city: "Naypyidaw" },
  { country: "Kenya", city: "Nairobi" },
  { country: "South Korea", city: "Seoul" },
  { country: "Colombia", city: "Bogotá" },
  { country: "Spain", city: "Madrid" },
  { country: "Uganda", city: "Kampala" },
  { country: "Argentina", city: "Buenos Aires" },
  { country: "Algeria", city: "Algiers" },
  { country: "Sudan", city: "Khartoum" },
  { country: "Ukraine", city: "Kyiv" },
  { country: "Iraq", city: "Baghdad" },
  { country: "Afghanistan", city: "Kabul" },
  { country: "Poland", city: "Warsaw" },
  { country: "Canada", city: "Ottawa" },
  { country: "Morocco", city: "Rabat" },
  { country: "Saudi Arabia", city: "Riyadh" },
  { country: "Uzbekistan", city: "Tashkent" },
  { country: "Peru", city: "Lima" },
  { country: "Malaysia", city: "Kuala Lumpur" },
  { country: "Angola", city: "Luanda" },
  { country: "Mozambique", city: "Maputo" },
  { country: "Ghana", city: "Accra" },
  { country: "Yemen", city: "Sana'a" },
  { country: "Nepal", city: "Kathmandu" },
  { country: "Venezuela", city: "Caracas" },
  { country: "Madagascar", city: "Antananarivo" },
  { country: "Cameroon", city: "Yaoundé" },
  { country: "Côte d'Ivoire", city: "Yamoussoukro" },
  { country: "North Korea", city: "Pyongyang" },
  { country: "Australia", city: "Canberra" },
  { country: "Niger", city: "Niamey" },
  { country: "Taiwan", city: "Taipei" },
  { country: "Sri Lanka", city: "Colombo" },
  { country: "Burkina Faso", city: "Ouagadougou" },
  { country: "Mali", city: "Bamako" },
  { country: "Romania", city: "Bucharest" },
  { country: "Malawi", city: "Lilongwe" },
  { country: "Syria", city: "Damascus" },
  { country: "Kazakhstan", city: "Nur-Sultan" },
  { country: "Zambia", city: "Lusaka" },
  { country: "Congo", city: "Brazzaville" },
  { country: "Honduras", city: "Tegucigalpa" },
  { country: "Nicaragua", city: "Managua" },
  { country: "El Salvador", city: "San Salvador" },
  { country: "Costa Rica", city: "San José" },
  { country: "Panama", city: "Panama City" },
  { country: "Uruguay", city: "Montevideo" },
  { country: "Jamaica", city: "Kingston" },
  { country: "Guyana", city: "Georgetown" },
  { country: "Suriname", city: "Paramaribo" },
  { country: "Bahamas", city: "Nassau" },
  { country: "Barbados", city: "Bridgetown" },
  { country: "Saint Lucia", city: "Castries" },
  { country: "Grenada", city: "St. George's" },
  { country: "Dominica", city: "Roseau" },
  { country: "Chile", city: "Santiago" },
  { country: "Ecuador", city: "Quito" },
  { country: "Cuba", city: "Havana" },
  { country: "Bolivia", city: "La Paz" },
  { country: "Haiti", city: "Port-au-Prince" },
  { country: "Paraguay", city: "Asunción" },
  { country: "Honduras", city: "Tegucigalpa" },
  { country: "Nicaragua", city: "Managua" },
  { country: "Panama", city: "Panama City" },
  { country: "Uruguay", city: "Montevideo" },
  { country: "Jamaica", city: "Kingston" },
  { country: "Guyana", city: "Georgetown" },
  { country: "Suriname", city: "Paramaribo" },
  { country: "Bahamas", city: "Nassau" },
  { country: "Barbados", city: "Bridgetown" },
  { country: "Saint Lucia", city: "Castries" },
  { country: "Saint Vincent and the Grenadines", city: "Kingstown" },
  { country: "Grenada", city: "St. George's" },
  { country: "Dominica", city: "Roseau" },
];
